# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'hajjApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # Pods for hajjApp

end
